name: example-environment
channels:
  - conda-forge
dependencies:
  - pythonocc-core
  - svgwrite
  - ipywidgets
  - numpy
  - pythreejs
  
  #- pip
  #- pip:
  #  - nbgitpuller
  #  - sphinx-gallery
  #  - pandas
  #  - matplotlib
    #- x3d
